namespace AgentDeck.Core;

/// <summary>
/// The icons a terminal can get (Fluent Emoji names from wwwroot/icons/fluent.json), each described in terms of the
/// work it stands for: these are the options the TypeSafe classifier chooses between (at most 255).
/// </summary>
static class SessionIcons
{
    public static readonly (string Name, string Description)[] Options =
    [
        ("bug", "Fixing a bug, crash or broken behaviour"),
        ("lady-beetle", "Tracking down a small, subtle or flaky bug"),
        ("test-tube", "Writing or running tests, test suites, assertions"),
        ("microscope", "Investigating in depth, diagnosing, root-cause analysis"),
        ("petri-dish", "Experiments, prototypes, spikes, trying things out"),
        ("magnifying-glass-tilted-left", "Searching or exploring the codebase, reading code to understand it"),
        ("detective", "Investigating a mystery, tracing where something comes from"),
        ("eyes", "Code review, looking over changes, watching output"),
        ("judge", "Evaluating, grading, judging quality, evals"),
        ("thinking-face", "Planning, weighing options, answering a question, discussion"),
        ("brain", "AI, machine learning, LLM prompts, models, embeddings"),
        ("robot", "Agents, automation, bots, AI tooling, subagents"),
        ("light-bulb", "New idea, feature design, brainstorming"),
        ("rocket", "Deploying, shipping, releasing, launching to production"),
        ("package", "Dependencies, packages, npm/NuGet/pip, bundling, builds"),
        ("building-construction", "Scaffolding a new project or building a big new feature"),
        ("construction", "Work in progress, large refactor under way"),
        ("hammer-and-wrench", "General build and fix work, tooling, maintenance"),
        ("wrench", "Configuration tweaks, small fixes, settings"),
        ("gear", "Settings, configuration files, environment setup"),
        ("nut-and-bolt", "Low-level internals, plumbing, wiring components together"),
        ("toolbox", "Developer tools, scripts, utilities, CLI tooling"),
        ("broom", "Cleanup, removing dead code, lint fixes, tidying up"),
        ("recycling-symbol", "Refactoring, restructuring, reusing code"),
        ("scissors", "Cutting code, trimming, splitting files apart"),
        ("link", "Integration, connecting services, APIs, webhooks, URLs"),
        ("electric-plug", "Plugins, adapters, connecting hardware or devices"),
        ("chains", "Coupling, dependency chains, pipelines"),
        ("locked", "Security, authentication, login, permissions, encryption"),
        ("key", "API keys, secrets, credentials, tokens"),
        ("shield", "Security hardening, validation, protection, safety checks"),
        ("identification-card", "User accounts, identity, profiles, sign-up"),
        ("busts-in-silhouette", "Users, teams, multi-user features, sharing"),
        ("globe-showing-americas", "Website, web app, internet, public pages"),
        ("globe-with-meridians", "Internationalisation, languages, translations"),
        ("spider-web", "Web scraping, crawling, networks of links"),
        ("world-map", "Routing, maps, navigation, site structure"),
        ("compass", "Choosing a direction, deciding an approach"),
        ("laptop", "Frontend app work, local development"),
        ("desktop-computer", "Desktop application, Windows app, native UI"),
        ("mobile-phone", "Mobile app, iOS, Android, responsive layouts"),
        ("keyboard", "Keyboard shortcuts, input handling, typing"),
        ("computer-mouse", "Mouse, clicks, drag and drop, UI interaction"),
        ("joystick", "Game controller, Stream Deck, hardware controls"),
        ("video-game", "Game development, gameplay"),
        ("artist-palette", "UI design, styling, CSS, colours, themes"),
        ("paintbrush", "Visual polish, redesign, styling tweaks"),
        ("framed-picture", "Images, icons, graphics, illustrations"),
        ("camera", "Screenshots, photos, capturing images"),
        ("movie-camera", "Video, recording, streaming media"),
        ("clapper-board", "Demo, presentation, video production"),
        ("musical-note", "Music, audio playback"),
        ("speaker-high-volume", "Sound effects, audio output, volume, chimes"),
        ("microphone", "Voice, speech, dictation, speech-to-text"),
        ("speech-balloon", "Chat, messaging, comments, conversation features"),
        ("megaphone", "Announcements, marketing copy, broadcasting"),
        ("bell", "Notifications, alerts, reminders"),
        ("envelope", "Email sending, mail templates, inbox"),
        ("incoming-envelope", "Incoming messages, webhooks received, email parsing"),
        ("telephone-receiver", "Phone calls, SMS, voice APIs"),
        ("memo", "Writing docs, README, notes, text content"),
        ("page-facing-up", "Editing a single file, a document or spec"),
        ("scroll", "Long documents, changelog, history, legacy code"),
        ("books", "Documentation, research, reference reading"),
        ("open-book", "Reading, guides, tutorials, a book or scripture"),
        ("church", "Bible, faith, church, religious content"),
        ("graduation-cap", "Learning, education, courses, study"),
        ("notebook", "Notebooks, journals, logs of work"),
        ("clipboard", "Checklists, task lists, TODOs, requirements"),
        ("spiral-notepad", "Meeting notes, planning notes, drafts"),
        ("pushpin", "Pinning, bookmarks, important items"),
        ("label", "Tags, labels, categories, naming things"),
        ("newspaper", "News, feeds, articles, blog posts"),
        ("card-file-box", "Database, records, storage, data model, SQL"),
        ("file-cabinet", "File storage, archives, backups"),
        ("open-file-folder", "File system, folders, project structure"),
        ("floppy-disk", "Saving, persistence, caching"),
        ("dna", "Schemas, data structures, types, core model of the system"),
        ("alembic", "Data transformation, migrations, ETL"),
        ("bar-chart", "Analytics, metrics, charts, dashboards, reporting"),
        ("chart-increasing", "Performance improvement, growth, optimisation"),
        ("chart-decreasing", "Regressions, reducing size, cost cutting"),
        ("abacus", "Calculations, math, algorithms, counting"),
        ("straight-ruler", "Layout, measurements, spacing, sizing"),
        ("triangular-ruler", "Architecture, system design, precise structure"),
        ("balance-scale", "Comparisons, trade-offs, legal, licensing"),
        ("money-bag", "Payments, billing, pricing, revenue"),
        ("credit-card", "Checkout, payment processing, Stripe"),
        ("shopping-cart", "E-commerce, store, cart, orders"),
        ("receipt", "Invoices, receipts, transactions"),
        ("calendar", "Scheduling, dates, calendar features"),
        ("alarm-clock", "Timers, cron jobs, scheduled tasks"),
        ("hourglass-not-done", "Waiting on slow operations, timeouts, long-running jobs"),
        ("stopwatch", "Latency, timing, benchmarks"),
        ("high-voltage", "Speed, performance, fast paths"),
        ("battery", "Power usage, energy efficiency, resources"),
        ("fire", "Urgent hotfix, production incident, something on fire"),
        ("police-car", "Alerts, incidents, on-call emergency"),
        ("warning", "Warnings, risky changes, deprecations"),
        ("cross-mark", "Errors, failures, broken build"),
        ("stop-sign", "Blocked, stopped, halted, needs a decision"),
        ("check-mark-button", "Done, passing, verified, approved"),
        ("party-popper", "Celebration, finished milestone, success"),
        ("trophy", "Achievement, completed goal"),
        ("bullseye", "Focused goal, precision, accuracy"),
        ("puzzle-piece", "Hard problem, fitting pieces together"),
        ("crystal-ball", "Predictions, forecasting, estimates"),
        ("sparkles", "Polish, new shiny feature, AI generation"),
        ("magic-wand", "Code generation, automatic transformations"),
        ("satellite-antenna", "Networking, API calls, HTTP, telemetry"),
        ("satellite", "Remote servers, infrastructure"),
        ("cloud", "Cloud services, Azure, AWS, hosting"),
        ("cloud-with-lightning", "Cloud outage, infrastructure problems"),
        ("counterclockwise-arrows-button", "Sync, retry, refresh, reload, loops"),
        ("right-arrow-curving-left", "Undo, revert, rollback"),
        ("shuffle-tracks-button", "Git branches, merging, rebasing, shuffling"),
        ("octopus", "GitHub, pull requests, many things in parallel"),
        ("card-index-dividers", "Organising, sorting, categorising"),
        ("inbox-tray", "Import, ingestion, uploads"),
        ("outbox-tray", "Export, publishing, downloads"),
        ("window", "Windows, dialogs, modals, UI panels"),
        ("door", "Onboarding, entry points, sign-in and sign-out"),
        ("house", "Home page, landing page"),
        ("classical-building", "Enterprise, institutions, legacy architecture"),
        ("cityscape", "Large system, many services, microservices"),
        ("factory", "CI/CD, build pipelines, batch processing"),
        ("locomotive", "Workflows, job runners, queues"),
        ("racing-car", "Racing through a task, speed"),
        ("anchor", "Stability, pinning versions, reliability"),
        ("mountain", "Big challenge, hard task"),
        ("volcano", "Cascade of errors, things blowing up"),
        ("evergreen-tree", "Trees, hierarchies, nested structures"),
        ("seedling", "New project, first steps, initial setup"),
        ("four-leaf-clover", "Randomness, probabilities, luck"),
        ("owl", "Careful review, wisdom, late-night work"),
        ("turtle", "Slow code, performance problems"),
        ("snail", "Very slow, sluggish, lag"),
        ("honeybee", "Busy work, many workers, background jobs"),
        ("spider", "Crawlers, bots"),
        ("dragon", "Huge legacy beast, epic task"),
        ("ghost", "Phantom issues, hidden processes, things that vanish"),
        ("skull", "Killing processes, dead code, fatal errors"),
        ("alien-monster", "Weird unexpected behaviour"),
        ("man-technologist", "General coding with no clearer subject"),
        ("scientist", "Research, data science, experiments"),
        ("teacher", "Explaining, teaching, lessons"),
        ("handshake", "Agreement, contracts, collaboration"),
        ("waving-hand", "Greeting, hello world, just getting started"),
        ("television", "Screens, displays, rendering output"),
        ("printer", "Printing, PDF output, reports"),
        ("input-latin-letters", "Text processing, strings, fonts, typography"),
        ("input-numbers", "Numbers, numeric parsing, IDs, versions"),
        ("up-button", "Upgrades, version bumps, updating"),
        ("new-button", "Brand-new feature, fresh start"),
        ("sos-button", "Stuck, asking for help"),
        ("red-question-mark", "Unclear problem, waiting on an answer from the user"),
        ("red-exclamation-mark", "Important, attention needed, action required"),
        ("hot-beverage", "Idle, finished, waiting for the user"),
        ("zzz", "Asleep, no activity at all"),
    ];
}
